server:
  shutdown: immediate
  port: 8082

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

hmpps.auth.url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

prison:
  api:
    url: https://prison-api-dev.prison.service.justice.gov.uk

personal:
  relationships:
    api:
      url: https://personal-relationships-api-dev.hmpps.service.justice.gov.uk

api:
  timeout: 10s
